using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using MOMOKA.MetaData;
using MOMOKA.Shader;
using MOMOKA.Common;
using System.IO;
using System;
using System.Text;
using UnityEditor;

namespace MOMOKA.Generator
{
    public class MMKShaderContext
    {
        public string ShaderPath { get; protected set; }
        public string ShaderUniformPath { get; protected set; }
        public string ShaderLibraryDirectory { get; protected set; }

        public string ShaderName { get; protected set; }
        public string ShaderFallback { get; protected set; }
        public string ShaderEditor { get; protected set; }

        public List<MMKShaderProperty> ShaderProperties = new List<MMKShaderProperty>();

        public List<MMKSubShaderContext> SubShaders = new List<MMKSubShaderContext>();

        public void GenerateShader()
        {
            if (string.IsNullOrEmpty(ShaderName))
            {
                ShaderName = "MOMOKA/New Shader";
            }

            if (string.IsNullOrEmpty(ShaderPath))
            {
                ShaderPath = MMKUtils.MakeValidFullPath(ShaderName, ".shader");
            }

            if (string.IsNullOrEmpty(ShaderUniformPath))
            {
                ShaderUniformPath = Path.ChangeExtension(ShaderPath, "_Properties.hlsl");
            }
            else if (!ShaderUniformPath.EndsWith(".hlsl", StringComparison.OrdinalIgnoreCase))
            {
                ShaderUniformPath = Path.ChangeExtension(ShaderUniformPath, ".hlsl");
            }

            ShaderLibraryDirectory = Path.GetDirectoryName(ShaderPath + "/ShaderLibrary");

            // Generate

            GenerateShaderFile();

            GenerateShaderPropertyFile();

            CopyIncludeFiles();
        }

        protected void GenerateShaderFile()
        {
            MMKFileBuilder shaderBuilder = new MMKFileBuilder(ShaderPath);
            shaderBuilder.AppendLine("// This file is auto-generated by MOMOKA. Do not modify it directly.");
            shaderBuilder.AppendLine("// Generated on " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            shaderBuilder.AppendLine();
            shaderBuilder.AppendLine($"Shader \"{ShaderName}\"");
            shaderBuilder.IncreaseIndent("{");

            // Generate properties
            shaderBuilder.AppendLine("Properties");
            shaderBuilder.IncreaseIndent("{");
            foreach (MMKShaderProperty property in ShaderProperties)
            {
                shaderBuilder.AppendLine(property.GenerateMaterialProperty());
            }
            shaderBuilder.DecreaseIndent("}");

            // Generate sub shaders
            foreach (MMKSubShaderContext subShader in SubShaders)
            {
                shaderBuilder.AppendLine("SubShader");
                shaderBuilder.IncreaseIndent("{");

                subShader.GenerateSubShader(shaderBuilder);

                shaderBuilder.DecreaseIndent("}");
            }

            if (!string.IsNullOrEmpty(ShaderFallback))
            {
                shaderBuilder.AppendLine($"Fallback \"{ShaderFallback}\"");
            }
            if (!string.IsNullOrEmpty(ShaderEditor))
            {
                shaderBuilder.AppendLine($"CustomEditor \"{ShaderEditor}\"");
            }
            shaderBuilder.DecreaseIndent("}");

            shaderBuilder.WriteFile();
        }

        protected void GenerateShaderPropertyFile()
        {
            MMKFileBuilder propertyBuilder = new MMKFileBuilder(ShaderUniformPath);
            propertyBuilder.AppendLine("// This file is auto-generated by MOMOKA. Do not modify it directly.");
            propertyBuilder.AppendLine("// Generated on " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            propertyBuilder.AppendLine();

            Dictionary<string, List<MMKShaderProperty>> propertiesByBuffer = new Dictionary<string, List<MMKShaderProperty>>();
            List<MMKShaderProperty> globalProperties = new List<MMKShaderProperty>();
            foreach (MMKShaderProperty property in ShaderProperties)
            {
                if (property is MMKShaderPropertyTexture || (property.ShaderDeclaration == ShaderPropertyDeclarationType.Global && string.IsNullOrEmpty(property.ConstantBufferName)))
                {
                    globalProperties.Add(property);
                }
                else
                {
                    List<MMKShaderProperty> bufferdProperties;
                    switch (property.ShaderDeclaration)
                    {
                        case ShaderPropertyDeclarationType.Global:
                            if (!propertiesByBuffer.TryGetValue(property.ConstantBufferName, out bufferdProperties))
                            {
                                bufferdProperties = new List<MMKShaderProperty>();
                                propertiesByBuffer.Add(property.ConstantBufferName, bufferdProperties);
                            }
                            bufferdProperties.Add(property);
                            break;
                        case ShaderPropertyDeclarationType.PerMaterial:
                            if (!propertiesByBuffer.TryGetValue("UnityPerMaterial", out bufferdProperties))
                            {
                                bufferdProperties = new List<MMKShaderProperty>();
                                propertiesByBuffer.Add("UnityPerMaterial", bufferdProperties);
                            }
                            bufferdProperties.Add(property);
                            break;
                        default:
                            break;
                    }
                }
            }

            foreach (KeyValuePair<string, List<MMKShaderProperty>> uniform in propertiesByBuffer)
            {
                propertyBuilder.IncreaseIndent($"CBUFFER_START({uniform.Key})");
                foreach (MMKShaderProperty property in uniform.Value)
                {
                    propertyBuilder.AppendLine(property.GenerateShaderUniform());
                }
                propertyBuilder.DecreaseIndent("CBUFFER_END");
                propertyBuilder.AppendLine();
            }
            propertyBuilder.AppendLine("// Global properties");
            propertyBuilder.AppendLine();
            foreach (MMKShaderProperty property in globalProperties)
            {
                propertyBuilder.AppendLine(property.GenerateShaderUniform());
            }
            propertyBuilder.AppendLine();

            propertyBuilder.WriteFile();
        }

        protected void CopyIncludeFiles()
        {
            if (Directory.Exists(ShaderLibraryDirectory))
            {
                Directory.Delete(ShaderLibraryDirectory, true);
            }
            Directory.CreateDirectory(ShaderLibraryDirectory);

            // TODO: Copy necessary include files to the shader library directory
        }
    }

    public class MMKSubShaderContext
    {
        public int Lod;

        public List<MMKShaderPass> Passes = new List<MMKShaderPass>();

        public List<MMKShaderFeature> ShaderFeatures = new List<MMKShaderFeature>();

        public Dictionary<MMKShaderInjectPoint, MMKShaderCodeSnap> ShaderCodes = new Dictionary<MMKShaderInjectPoint, MMKShaderCodeSnap>();

        public void GenerateSubShader(MMKFileBuilder builder)
        {
            // TODO: Generate shader features and shader code snaps
        }
    }
}
